baseurl = "https://shagu.gitlab.io/arch-install/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "arch-install"
canonifyurls  = false

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "A Simple Archlinux Installer"
  logo = "arch-install.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Eric Mauser"
  email = "shagu@fnordpipe.org"
  gitlab = "shagu"

[[menu.main]]
    identifier = "download"
    name = "Downloads"
    weight = 2

[[menu.main]]
    parent = "download"
    name = "Installer ISO"
    url = "https://gitlab.com/shagu/arch-install/-/jobs/artifacts/gitlab-ci/raw/archlinux-installer.iso?job=default"
    weight = 1

[[menu.main]]
    parent = "download"
    name = "Installer SSH ISO"
    url = "https://gitlab.com/shagu/arch-install/-/jobs/artifacts/gitlab-ci/raw/archlinux-installer-ssh.iso?job=ssh"
    weight = 2

[[menu.main]]
    parent = "download"
    name = "Installer Script"
    url = "https://gitlab.com/shagu/arch-install/raw/master/arch-install.sh"
    weight = 3

[[menu.main]]
    name = "git"
    url = "https://gitlab.com/shagu/arch-install"
    weight = 3
